# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CurrentUserResponseModel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, first_name: str=None, last_name: str=None, other_name: str=None, email: str=None, phone: str=None, birthday: date=None, is_admin: bool=None):  # noqa: E501
        """CurrentUserResponseModel - a model defined in Swagger

        :param first_name: The first_name of this CurrentUserResponseModel.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this CurrentUserResponseModel.  # noqa: E501
        :type last_name: str
        :param other_name: The other_name of this CurrentUserResponseModel.  # noqa: E501
        :type other_name: str
        :param email: The email of this CurrentUserResponseModel.  # noqa: E501
        :type email: str
        :param phone: The phone of this CurrentUserResponseModel.  # noqa: E501
        :type phone: str
        :param birthday: The birthday of this CurrentUserResponseModel.  # noqa: E501
        :type birthday: date
        :param is_admin: The is_admin of this CurrentUserResponseModel.  # noqa: E501
        :type is_admin: bool
        """
        self.swagger_types = {
            'first_name': str,
            'last_name': str,
            'other_name': str,
            'email': str,
            'phone': str,
            'birthday': date,
            'is_admin': bool
        }

        self.attribute_map = {
            'first_name': 'first_name',
            'last_name': 'last_name',
            'other_name': 'other_name',
            'email': 'email',
            'phone': 'phone',
            'birthday': 'birthday',
            'is_admin': 'is_admin'
        }
        self._first_name = first_name
        self._last_name = last_name
        self._other_name = other_name
        self._email = email
        self._phone = phone
        self._birthday = birthday
        self._is_admin = is_admin

    @classmethod
    def from_dict(cls, dikt) -> 'CurrentUserResponseModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CurrentUserResponseModel of this CurrentUserResponseModel.  # noqa: E501
        :rtype: CurrentUserResponseModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def first_name(self) -> str:
        """Gets the first_name of this CurrentUserResponseModel.


        :return: The first_name of this CurrentUserResponseModel.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this CurrentUserResponseModel.


        :param first_name: The first_name of this CurrentUserResponseModel.
        :type first_name: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this CurrentUserResponseModel.


        :return: The last_name of this CurrentUserResponseModel.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this CurrentUserResponseModel.


        :param last_name: The last_name of this CurrentUserResponseModel.
        :type last_name: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501

        self._last_name = last_name

    @property
    def other_name(self) -> str:
        """Gets the other_name of this CurrentUserResponseModel.


        :return: The other_name of this CurrentUserResponseModel.
        :rtype: str
        """
        return self._other_name

    @other_name.setter
    def other_name(self, other_name: str):
        """Sets the other_name of this CurrentUserResponseModel.


        :param other_name: The other_name of this CurrentUserResponseModel.
        :type other_name: str
        """
        if other_name is None:
            raise ValueError("Invalid value for `other_name`, must not be `None`")  # noqa: E501

        self._other_name = other_name

    @property
    def email(self) -> str:
        """Gets the email of this CurrentUserResponseModel.


        :return: The email of this CurrentUserResponseModel.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this CurrentUserResponseModel.


        :param email: The email of this CurrentUserResponseModel.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def phone(self) -> str:
        """Gets the phone of this CurrentUserResponseModel.


        :return: The phone of this CurrentUserResponseModel.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this CurrentUserResponseModel.


        :param phone: The phone of this CurrentUserResponseModel.
        :type phone: str
        """
        if phone is None:
            raise ValueError("Invalid value for `phone`, must not be `None`")  # noqa: E501

        self._phone = phone

    @property
    def birthday(self) -> date:
        """Gets the birthday of this CurrentUserResponseModel.


        :return: The birthday of this CurrentUserResponseModel.
        :rtype: date
        """
        return self._birthday

    @birthday.setter
    def birthday(self, birthday: date):
        """Sets the birthday of this CurrentUserResponseModel.


        :param birthday: The birthday of this CurrentUserResponseModel.
        :type birthday: date
        """
        if birthday is None:
            raise ValueError("Invalid value for `birthday`, must not be `None`")  # noqa: E501

        self._birthday = birthday

    @property
    def is_admin(self) -> bool:
        """Gets the is_admin of this CurrentUserResponseModel.


        :return: The is_admin of this CurrentUserResponseModel.
        :rtype: bool
        """
        return self._is_admin

    @is_admin.setter
    def is_admin(self, is_admin: bool):
        """Sets the is_admin of this CurrentUserResponseModel.


        :param is_admin: The is_admin of this CurrentUserResponseModel.
        :type is_admin: bool
        """
        if is_admin is None:
            raise ValueError("Invalid value for `is_admin`, must not be `None`")  # noqa: E501

        self._is_admin = is_admin
