# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.validation_error import ValidationError  # noqa: F401,E501
from swagger_server import util


class HTTPValidationError(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, detail: List[ValidationError]=None):  # noqa: E501
        """HTTPValidationError - a model defined in Swagger

        :param detail: The detail of this HTTPValidationError.  # noqa: E501
        :type detail: List[ValidationError]
        """
        self.swagger_types = {
            'detail': List[ValidationError]
        }

        self.attribute_map = {
            'detail': 'detail'
        }
        self._detail = detail

    @classmethod
    def from_dict(cls, dikt) -> 'HTTPValidationError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HTTPValidationError of this HTTPValidationError.  # noqa: E501
        :rtype: HTTPValidationError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def detail(self) -> List[ValidationError]:
        """Gets the detail of this HTTPValidationError.


        :return: The detail of this HTTPValidationError.
        :rtype: List[ValidationError]
        """
        return self._detail

    @detail.setter
    def detail(self, detail: List[ValidationError]):
        """Sets the detail of this HTTPValidationError.


        :param detail: The detail of this HTTPValidationError.
        :type detail: List[ValidationError]
        """

        self._detail = detail
