# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.cities_hint_model import CitiesHintModel  # noqa: F401,E501
from swagger_server import util


class PrivateUsersListHintMetaModel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, city: List[CitiesHintModel]=None):  # noqa: E501
        """PrivateUsersListHintMetaModel - a model defined in Swagger

        :param city: The city of this PrivateUsersListHintMetaModel.  # noqa: E501
        :type city: List[CitiesHintModel]
        """
        self.swagger_types = {
            'city': List[CitiesHintModel]
        }

        self.attribute_map = {
            'city': 'city'
        }
        self._city = city

    @classmethod
    def from_dict(cls, dikt) -> 'PrivateUsersListHintMetaModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PrivateUsersListHintMetaModel of this PrivateUsersListHintMetaModel.  # noqa: E501
        :rtype: PrivateUsersListHintMetaModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def city(self) -> List[CitiesHintModel]:
        """Gets the city of this PrivateUsersListHintMetaModel.


        :return: The city of this PrivateUsersListHintMetaModel.
        :rtype: List[CitiesHintModel]
        """
        return self._city

    @city.setter
    def city(self, city: List[CitiesHintModel]):
        """Sets the city of this PrivateUsersListHintMetaModel.


        :param city: The city of this PrivateUsersListHintMetaModel.
        :type city: List[CitiesHintModel]
        """
        if city is None:
            raise ValueError("Invalid value for `city`, must not be `None`")  # noqa: E501

        self._city = city
