# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PrivateCreateUserModel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, first_name: str=None, last_name: str=None, other_name: str=None, email: str=None, phone: str=None, birthday: date=None, city: int=None, additional_info: str=None, is_admin: bool=None, password: str=None):  # noqa: E501
        """PrivateCreateUserModel - a model defined in Swagger

        :param first_name: The first_name of this PrivateCreateUserModel.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this PrivateCreateUserModel.  # noqa: E501
        :type last_name: str
        :param other_name: The other_name of this PrivateCreateUserModel.  # noqa: E501
        :type other_name: str
        :param email: The email of this PrivateCreateUserModel.  # noqa: E501
        :type email: str
        :param phone: The phone of this PrivateCreateUserModel.  # noqa: E501
        :type phone: str
        :param birthday: The birthday of this PrivateCreateUserModel.  # noqa: E501
        :type birthday: date
        :param city: The city of this PrivateCreateUserModel.  # noqa: E501
        :type city: int
        :param additional_info: The additional_info of this PrivateCreateUserModel.  # noqa: E501
        :type additional_info: str
        :param is_admin: The is_admin of this PrivateCreateUserModel.  # noqa: E501
        :type is_admin: bool
        :param password: The password of this PrivateCreateUserModel.  # noqa: E501
        :type password: str
        """
        self.swagger_types = {
            'first_name': str,
            'last_name': str,
            'other_name': str,
            'email': str,
            'phone': str,
            'birthday': date,
            'city': int,
            'additional_info': str,
            'is_admin': bool,
            'password': str
        }

        self.attribute_map = {
            'first_name': 'first_name',
            'last_name': 'last_name',
            'other_name': 'other_name',
            'email': 'email',
            'phone': 'phone',
            'birthday': 'birthday',
            'city': 'city',
            'additional_info': 'additional_info',
            'is_admin': 'is_admin',
            'password': 'password'
        }
        self._first_name = first_name
        self._last_name = last_name
        self._other_name = other_name
        self._email = email
        self._phone = phone
        self._birthday = birthday
        self._city = city
        self._additional_info = additional_info
        self._is_admin = is_admin
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'PrivateCreateUserModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PrivateCreateUserModel of this PrivateCreateUserModel.  # noqa: E501
        :rtype: PrivateCreateUserModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def first_name(self) -> str:
        """Gets the first_name of this PrivateCreateUserModel.


        :return: The first_name of this PrivateCreateUserModel.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this PrivateCreateUserModel.


        :param first_name: The first_name of this PrivateCreateUserModel.
        :type first_name: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this PrivateCreateUserModel.


        :return: The last_name of this PrivateCreateUserModel.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this PrivateCreateUserModel.


        :param last_name: The last_name of this PrivateCreateUserModel.
        :type last_name: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501

        self._last_name = last_name

    @property
    def other_name(self) -> str:
        """Gets the other_name of this PrivateCreateUserModel.


        :return: The other_name of this PrivateCreateUserModel.
        :rtype: str
        """
        return self._other_name

    @other_name.setter
    def other_name(self, other_name: str):
        """Sets the other_name of this PrivateCreateUserModel.


        :param other_name: The other_name of this PrivateCreateUserModel.
        :type other_name: str
        """

        self._other_name = other_name

    @property
    def email(self) -> str:
        """Gets the email of this PrivateCreateUserModel.


        :return: The email of this PrivateCreateUserModel.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this PrivateCreateUserModel.


        :param email: The email of this PrivateCreateUserModel.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def phone(self) -> str:
        """Gets the phone of this PrivateCreateUserModel.


        :return: The phone of this PrivateCreateUserModel.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this PrivateCreateUserModel.


        :param phone: The phone of this PrivateCreateUserModel.
        :type phone: str
        """

        self._phone = phone

    @property
    def birthday(self) -> date:
        """Gets the birthday of this PrivateCreateUserModel.


        :return: The birthday of this PrivateCreateUserModel.
        :rtype: date
        """
        return self._birthday

    @birthday.setter
    def birthday(self, birthday: date):
        """Sets the birthday of this PrivateCreateUserModel.


        :param birthday: The birthday of this PrivateCreateUserModel.
        :type birthday: date
        """

        self._birthday = birthday

    @property
    def city(self) -> int:
        """Gets the city of this PrivateCreateUserModel.


        :return: The city of this PrivateCreateUserModel.
        :rtype: int
        """
        return self._city

    @city.setter
    def city(self, city: int):
        """Sets the city of this PrivateCreateUserModel.


        :param city: The city of this PrivateCreateUserModel.
        :type city: int
        """

        self._city = city

    @property
    def additional_info(self) -> str:
        """Gets the additional_info of this PrivateCreateUserModel.


        :return: The additional_info of this PrivateCreateUserModel.
        :rtype: str
        """
        return self._additional_info

    @additional_info.setter
    def additional_info(self, additional_info: str):
        """Sets the additional_info of this PrivateCreateUserModel.


        :param additional_info: The additional_info of this PrivateCreateUserModel.
        :type additional_info: str
        """

        self._additional_info = additional_info

    @property
    def is_admin(self) -> bool:
        """Gets the is_admin of this PrivateCreateUserModel.


        :return: The is_admin of this PrivateCreateUserModel.
        :rtype: bool
        """
        return self._is_admin

    @is_admin.setter
    def is_admin(self, is_admin: bool):
        """Sets the is_admin of this PrivateCreateUserModel.


        :param is_admin: The is_admin of this PrivateCreateUserModel.
        :type is_admin: bool
        """
        if is_admin is None:
            raise ValueError("Invalid value for `is_admin`, must not be `None`")  # noqa: E501

        self._is_admin = is_admin

    @property
    def password(self) -> str:
        """Gets the password of this PrivateCreateUserModel.


        :return: The password of this PrivateCreateUserModel.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this PrivateCreateUserModel.


        :param password: The password of this PrivateCreateUserModel.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password
