# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UpdateUserResponseModel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, first_name: str=None, last_name: str=None, other_name: str=None, email: str=None, phone: str=None, birthday: date=None):  # noqa: E501
        """UpdateUserResponseModel - a model defined in Swagger

        :param id: The id of this UpdateUserResponseModel.  # noqa: E501
        :type id: int
        :param first_name: The first_name of this UpdateUserResponseModel.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this UpdateUserResponseModel.  # noqa: E501
        :type last_name: str
        :param other_name: The other_name of this UpdateUserResponseModel.  # noqa: E501
        :type other_name: str
        :param email: The email of this UpdateUserResponseModel.  # noqa: E501
        :type email: str
        :param phone: The phone of this UpdateUserResponseModel.  # noqa: E501
        :type phone: str
        :param birthday: The birthday of this UpdateUserResponseModel.  # noqa: E501
        :type birthday: date
        """
        self.swagger_types = {
            'id': int,
            'first_name': str,
            'last_name': str,
            'other_name': str,
            'email': str,
            'phone': str,
            'birthday': date
        }

        self.attribute_map = {
            'id': 'id',
            'first_name': 'first_name',
            'last_name': 'last_name',
            'other_name': 'other_name',
            'email': 'email',
            'phone': 'phone',
            'birthday': 'birthday'
        }
        self._id = id
        self._first_name = first_name
        self._last_name = last_name
        self._other_name = other_name
        self._email = email
        self._phone = phone
        self._birthday = birthday

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateUserResponseModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateUserResponseModel of this UpdateUserResponseModel.  # noqa: E501
        :rtype: UpdateUserResponseModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this UpdateUserResponseModel.


        :return: The id of this UpdateUserResponseModel.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this UpdateUserResponseModel.


        :param id: The id of this UpdateUserResponseModel.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def first_name(self) -> str:
        """Gets the first_name of this UpdateUserResponseModel.


        :return: The first_name of this UpdateUserResponseModel.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this UpdateUserResponseModel.


        :param first_name: The first_name of this UpdateUserResponseModel.
        :type first_name: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this UpdateUserResponseModel.


        :return: The last_name of this UpdateUserResponseModel.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this UpdateUserResponseModel.


        :param last_name: The last_name of this UpdateUserResponseModel.
        :type last_name: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501

        self._last_name = last_name

    @property
    def other_name(self) -> str:
        """Gets the other_name of this UpdateUserResponseModel.


        :return: The other_name of this UpdateUserResponseModel.
        :rtype: str
        """
        return self._other_name

    @other_name.setter
    def other_name(self, other_name: str):
        """Sets the other_name of this UpdateUserResponseModel.


        :param other_name: The other_name of this UpdateUserResponseModel.
        :type other_name: str
        """
        if other_name is None:
            raise ValueError("Invalid value for `other_name`, must not be `None`")  # noqa: E501

        self._other_name = other_name

    @property
    def email(self) -> str:
        """Gets the email of this UpdateUserResponseModel.


        :return: The email of this UpdateUserResponseModel.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UpdateUserResponseModel.


        :param email: The email of this UpdateUserResponseModel.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def phone(self) -> str:
        """Gets the phone of this UpdateUserResponseModel.


        :return: The phone of this UpdateUserResponseModel.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this UpdateUserResponseModel.


        :param phone: The phone of this UpdateUserResponseModel.
        :type phone: str
        """
        if phone is None:
            raise ValueError("Invalid value for `phone`, must not be `None`")  # noqa: E501

        self._phone = phone

    @property
    def birthday(self) -> date:
        """Gets the birthday of this UpdateUserResponseModel.


        :return: The birthday of this UpdateUserResponseModel.
        :rtype: date
        """
        return self._birthday

    @birthday.setter
    def birthday(self, birthday: date):
        """Sets the birthday of this UpdateUserResponseModel.


        :param birthday: The birthday of this UpdateUserResponseModel.
        :type birthday: date
        """
        if birthday is None:
            raise ValueError("Invalid value for `birthday`, must not be `None`")  # noqa: E501

        self._birthday = birthday
