# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.users_list_element_model import UsersListElementModel  # noqa: F401,E501
from swagger_server.models.users_list_meta_data_model import UsersListMetaDataModel  # noqa: F401,E501
from swagger_server import util


class UsersListResponseModel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[UsersListElementModel]=None, meta: UsersListMetaDataModel=None):  # noqa: E501
        """UsersListResponseModel - a model defined in Swagger

        :param data: The data of this UsersListResponseModel.  # noqa: E501
        :type data: List[UsersListElementModel]
        :param meta: The meta of this UsersListResponseModel.  # noqa: E501
        :type meta: UsersListMetaDataModel
        """
        self.swagger_types = {
            'data': List[UsersListElementModel],
            'meta': UsersListMetaDataModel
        }

        self.attribute_map = {
            'data': 'data',
            'meta': 'meta'
        }
        self._data = data
        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'UsersListResponseModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UsersListResponseModel of this UsersListResponseModel.  # noqa: E501
        :rtype: UsersListResponseModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[UsersListElementModel]:
        """Gets the data of this UsersListResponseModel.


        :return: The data of this UsersListResponseModel.
        :rtype: List[UsersListElementModel]
        """
        return self._data

    @data.setter
    def data(self, data: List[UsersListElementModel]):
        """Sets the data of this UsersListResponseModel.


        :param data: The data of this UsersListResponseModel.
        :type data: List[UsersListElementModel]
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    @property
    def meta(self) -> UsersListMetaDataModel:
        """Gets the meta of this UsersListResponseModel.


        :return: The meta of this UsersListResponseModel.
        :rtype: UsersListMetaDataModel
        """
        return self._meta

    @meta.setter
    def meta(self, meta: UsersListMetaDataModel):
        """Sets the meta of this UsersListResponseModel.


        :param meta: The meta of this UsersListResponseModel.
        :type meta: UsersListMetaDataModel
        """
        if meta is None:
            raise ValueError("Invalid value for `meta`, must not be `None`")  # noqa: E501

        self._meta = meta
