# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UsersListElementModel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, first_name: str=None, last_name: str=None, email: str=None):  # noqa: E501
        """UsersListElementModel - a model defined in Swagger

        :param id: The id of this UsersListElementModel.  # noqa: E501
        :type id: int
        :param first_name: The first_name of this UsersListElementModel.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this UsersListElementModel.  # noqa: E501
        :type last_name: str
        :param email: The email of this UsersListElementModel.  # noqa: E501
        :type email: str
        """
        self.swagger_types = {
            'id': int,
            'first_name': str,
            'last_name': str,
            'email': str
        }

        self.attribute_map = {
            'id': 'id',
            'first_name': 'first_name',
            'last_name': 'last_name',
            'email': 'email'
        }
        self._id = id
        self._first_name = first_name
        self._last_name = last_name
        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'UsersListElementModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UsersListElementModel of this UsersListElementModel.  # noqa: E501
        :rtype: UsersListElementModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this UsersListElementModel.


        :return: The id of this UsersListElementModel.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this UsersListElementModel.


        :param id: The id of this UsersListElementModel.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def first_name(self) -> str:
        """Gets the first_name of this UsersListElementModel.


        :return: The first_name of this UsersListElementModel.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this UsersListElementModel.


        :param first_name: The first_name of this UsersListElementModel.
        :type first_name: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this UsersListElementModel.


        :return: The last_name of this UsersListElementModel.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this UsersListElementModel.


        :param last_name: The last_name of this UsersListElementModel.
        :type last_name: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501

        self._last_name = last_name

    @property
    def email(self) -> str:
        """Gets the email of this UsersListElementModel.


        :return: The email of this UsersListElementModel.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UsersListElementModel.


        :param email: The email of this UsersListElementModel.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email
